apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: payment-gateway-config
          ports:
            - containerPort: {{ .Values.gateway.service.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: payment-gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
