apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - gateway-configmap.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - processor-deployment.yaml
  - processor-service.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - hpa.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
