apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-gateway
  namespace: rbih-payments
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payment-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-processor
  namespace: rbih-payments
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payment-processor
