---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-gateway
  namespace: rbih-payments
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-processor
  namespace: rbih-payments
